# ---
# - name: "Creates the backend directory"
#   file:
#     path: ~/backend
#     state: directory

# - name: "Unarchive backend folder"
#   unarchive:
#     src: /root/project/artifact.tar.gz
#     dest: ~/backend

# - name: "Install backend dependencies"
#   shell: |
#     cd ~/backend
#     ls
#     npm i

# - name: "Start up the node app using pm2"
#   shell: |
#     cd ~/backend/dist
#     pm2 stop default
#     pm2 start main.js
#   register: execute_node

# - name: "Print Message"
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"

# - name: "Configure pm2 to start as service"
#   become: true
#   shell: |
#     env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu

---
- name: "print working directory"
  shell: |
    pwd
    ls -lh

- name: Copy artifact.tar.gz to EC2
  copy:
    src: "project/artifact.tar.gz"
    dest: "~/"

- name: "Extract Artifact"
  shell: |
    tar -xvfz artifact.tar.gz
    ls -a